version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: todo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BE_API_URL: ${REACT_APP_BE_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data: