name: Deploy MERN APP TODO

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MERN_ENV
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /root/mern-app-todo

            echo "== Pull latest code =="
            git pull origin main

            echo "== Docker compose down =="
            docker-compose down

            echo "== Docker compose build =="
            docker-compose build

            echo "== Docker compose up -d =="
            docker-compose up -d